[project]
name = "odoo-addons-oca-data-protection"
version = "18.0.20250915.0"
dependencies = [
    "odoo-addon-base_export_anonymize==18.0.*",
    "odoo-addon-privacy==18.0.*",
    "odoo-addon-privacy_consent==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
